#!/usr/bin/python

lines = open("summary").read().splitlines()[1:]

with open("summary2", "w+") as f:
    for line in lines:
        tokens = line.split(", ")
        c, u, r = [float(v) for v in tokens[2:5]]
        ev = 7.6 * c + 3.23 + u + 1.17 + r
        f.write("%s, %s, %.3f, %.3f, %.3f, %.3f, %s\n" % (tokens[0], tokens[1], c, u, r, ev, tokens[-1]))
