#!/usr/bin/python2

import urllib.request, json, time, datetime

url_prefix = "https://steamcommunity.com/market/search/render/?search_descriptions=0&category_583950_Rarity%5B%5D="
url_suffix = "&sort_dir=desc&appid=583950&norender=1&count=500"
url_common = "tag_Rarity_Common"
url_uncommon = "tag_Rarity_Uncommon"
url_rare = "tag_Rarity_Rare"


def scrape(rarity_tag, dump=False):
    url_prefix + url_common + url_suffix
    with urllib.request.urlopen(url_prefix + rarity_tag + url_suffix) as url:
        raw = url.read().decode()
        if dump:
            now = int(time.time())
            open(rarity_tag, "a+").write(str(now) + " " + raw + "\n")
        return json.loads(raw)


def analyze(data):
    prices = {
        entry['name']:entry['sell_price']/100.0 for entry in data['results']
    }
    avg = 0.0 if len(prices) == 0 else sum(prices.values()) / len(prices)
    return prices, avg


count = -1
while True:
    count += 1
    dump = True if count % 10 == 0 else False
    data = scrape(url_common, dump)
    common_price, avg_common_price = analyze(data)

    data = scrape(url_uncommon, dump)
    uncommon_price, avg_uncommon_price = analyze(data)

    data = scrape(url_rare, dump)
    rare_price, avg_rare_price = analyze(data)

    price = {**common_price, **uncommon_price, **rare_price}

    heroes = ["Axe", "Drow Ranger", "Kanna", "Lich", "Tinker", "Legion Commander", "Lycan", "Phantom Assassin", "Omniknight", "Luna", "Bounty Hunter", "Ogre Magi", "Sniper", "Treant Protector", "Beastmaster", "Enchantress", "Sorla Khan", "Chen", "Zeus", "Ursa", "Skywrath Mage", "Winter Wyvern", "Venomancer", "Prellex", "Earthshaker", "Magnus", "Sven", "Dark Seer", "Debbi the Cunning", "Mazzie", "J'Muy the Wise", "Fahrvhan the Dreamer", "Necrophos", "Centaur Warrunner", "Abaddon", "Viper", "Timbersaw", "Keefe the Bold", "Tidehunter", "Crystal Maiden", "Bloodseeker", "Pugna", "Lion", "Storm Spirit", "Meepo", "Rix", "Outworld Devourer"]

    total = 0.0
    for cost in price:
            if cost in heroes:
                    total += price[cost]
            else:
                    total += 3 * price[cost]

    now = int(time.time())
    print(f"[ {datetime.datetime.now().strftime('%m-%d %H:%M ')}] - average common - {avg_common_price:{3}.{3}}, uncommon - {avg_uncommon_price:{3}.{3}}, rare - {avg_rare_price:{3}.{3}}, TOTAL - {total:.2f} $")
    open("summary_2", "a+").write(f"{now}, {datetime.datetime.now().strftime('%m-%d %H:%M')}, {avg_common_price:{3}.{3}}, {avg_uncommon_price:{3}.{3}}, {avg_rare_price:{3}.{3}}, {total:.2f}\n")

    time.sleep(60 - now % 60)
